services:
  mysql:
    image: mysql:8.0
    container_name: kelly_feed_mysql
    ports:
      - "33310:3306"
    volumes:
      - ./data/mysql/mysql:/var/lib/mysql
      - ./data/mysql/config/my.cnf:/etc/mysql/conf.d/my.cnf
    restart: no
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: community_feed
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
